pipeline {
    agent any

    environment {
        IMAGE = "abode-webapp"
        CONTAINER = "abode-container"
    }

    stages {

        stage('Build') {
            steps {
                echo "Building Docker Image"
                sh "docker build -t $IMAGE ."
            }
        }

        stage('Test') {
            steps {
                echo "Testing Application"
                sh """
                docker run -d --name test-container -p 8081:80 $IMAGE
                sleep 5
                curl http://localhost:8081
                docker stop test-container
                docker rm test-container
                """
            }
        }

        stage('Prod') {
            when {
                branch 'master'
            }
            steps {
                echo "Deploying to Production"
                sh """
                docker stop $CONTAINER || true
                docker rm $CONTAINER || true
                docker run -d -p 80:80 --name $CONTAINER $IMAGE
                """
            }
        }
    }
}